### ISSUE TITLE
overly eager github workflow review configuration

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/elton#48]
When using ```elton init ...``` to generate a GloBI index configuration, a default github review action is configured in an automatically generated file:

```.github/workflows/review.yml```

```
name: GloBI review by Elton

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  schedule:
    - cron: "* * * * 1"
...
```

Unfortunately, the line ```cron: "* * * * 1"``` triggers review *every minute* on Mondays. 

Suggest to change to: ```cron: "0 0 * * 1"``` to trigger a review on Monday at midnight according to the local server's clock.
